use std::str::FromStr;

grammar;

//om det är nummer returnerar det en sträng
// kan skriva Id => <> också

pub NumOrId: String = {
    Num => <>.to_string(),
    Id,
}

//+ innebär en eller flera gånger. usize unsigned integer med
// samma storlek som adressen
pub Num: usize = {
    r"[0-9]+" => usize::from_str(<>).unwrap(),
};

//namn på våra variabler
pub Id: String = { 
    r"([a-z]|[A-Z])([a-z]|[A-Z]|[0-9]|_)*" => String::from_str(<>).unwrap(),
};
